[package]
name = "lean-ir"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
lean-kernel = { path = "../lean-kernel" }

[dev-dependencies]