[package]
name = "lean-codegen"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
lean-ir = { path = "../lean-ir" }

[dev-dependencies]